#!/usr/bin/env python3
# This file is placed in the Public Domain.
#
# pylint: disable=C0116


"run tests"


import os
import sys


os.environ["PYTHONPATH"] = ":opr"

def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())
        sys.stdout.flush()


def main():
    popen("pytest opr")


if __name__ == "__main__":
    main()
